### ISSUE TITLE
Regression in AspNetCoreModule: %ASPNETCORE_PORT% doesn't get resolved from arguments

### ISSUE THREAD

**Issue by toburger** [SuaveIO/Suave.IIS#6]
As discussed in this issue, the ASPNETCORE_PORT should be read from the environment variables in the application instead of passing it through the command line arguments:
aspnet/AspNetCoreModule#117

**Comment by toburger** [comment]
aspnet/AspNetCoreModule#117

**Comment by TheJayMann** [comment]
Since you are now pulling the ASPNETCORE_PORT value from the environment, maybe you can pull ASPNETCORE_PATH as well.  I understand that reading from the environment is impure in nature, but, if done once at the beginning of `main`, would be just as good as getting it from the command line, and, as an added benefit, it would make the web.config file portable to any virtual directory, as there would no longer be a need to provide the virtual directory (possibly typing it in wrong in the process) in the web.config file.

**Comment by toburger** [comment]
The package shouldn't depend on AspNetCoreModule (which is Kestrel specific), it should use HttpPlatformHandler: https://github.com/aspnet/AspNetCoreModule/issues/117#issuecomment-311986150
So the long term solution is to revert back to HttpPlatformHandler.

**Comment by Dzoukr** [comment]
Hi @toburger and @TheJayMann - thanks for info and fixes, I was on vacation (away from PC). So now I am quite confused. I thought that HttpPlatformHandler is deprecated now and all new stuff (like app_offline.htm support) is added only into AspNetCoreModule?

**Comment by TheJayMann** [comment]
Given that AspNetCoreModule is open source, I figured that I'd make an attempt to fork the code as something supported outside of just AspNet Core, possibly with more useful features for other languages and stacks.  So far I have only had time to fork the project. I also haven't thought of a name for it.

**Comment by Dzoukr** [comment]
That sounds great, but it would lead to separate projects and it could lead to some problems like: how do you manage support/deploy of this new module to Azure?

I am still thinking about that @toburger PR reading port from env variable (even it is not 100% clean solution). Maybe as fallback if command arg is not resolved (to be sure it will work for both iis modules).

**Comment by Dzoukr** [comment]
Fixed now, thanks. 

https://github.com/SuaveIO/Suave.IIS/releases/tag/v2.3.0

Btw, I changed README.md to explain difference and how to use both modules. Anyway, thanks guys for help!
